// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGLinzc4D0c1s0IqKm4EgY3dYgAR3i-m0',
    appId: '1:600474936928:web:5d84ee178137f8e97ec505',
    messagingSenderId: '600474936928',
    projectId: 'pushnotidoanttlta',
    authDomain: 'pushnotidoanttlta.firebaseapp.com',
    storageBucket: 'pushnotidoanttlta.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO2wXpcKOwnCeXRmCe3uZsp49Ke7Tf08k',
    appId: '1:600474936928:android:411d1de744fa3f477ec505',
    messagingSenderId: '600474936928',
    projectId: 'pushnotidoanttlta',
    storageBucket: 'pushnotidoanttlta.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU9-TTlIk64N5HR3i2mr0o4BLubydTemw',
    appId: '1:600474936928:ios:5ea4174092351ba87ec505',
    messagingSenderId: '600474936928',
    projectId: 'pushnotidoanttlta',
    storageBucket: 'pushnotidoanttlta.appspot.com',
    iosBundleId: 'com.example.believederApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU9-TTlIk64N5HR3i2mr0o4BLubydTemw',
    appId: '1:600474936928:ios:5ea4174092351ba87ec505',
    messagingSenderId: '600474936928',
    projectId: 'pushnotidoanttlta',
    storageBucket: 'pushnotidoanttlta.appspot.com',
    iosBundleId: 'com.example.believederApp',
  );
}
